- name: variables form inventory 
  hosts: local
  connection: local
  tasks:
   - name: print couse info
     ansible.builtin.debug:
      msg: "Hello I am learning {{ COURSE }}, Course duration: {{ DURATION }}, trainer is {{ TRAINER }}"