[frontend]
172.31.13.227 COURSE=Devops with AWS DURATION=120hrs TRAINER=siva Ansible_user= ec2-user Ansible_pasword= DevOps321



[local]
localhost

[local:vars]
COURSE=Devops with AWS
DURATION=120hrs
TRAINER=siva 
